language: r

sudo: false

# Install xclip
addons:
  apt:
    packages:
      - xclip

# Ensure xclip can still run headlessly
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1


